version: "0.1"

tool_compose:
  id: "autosave"
  type_plan: free
  icon: "fas fa-pen-fancy text-xl"
  shortDescription: "Salve as melhorias e novos arquivos de forma autonoma"
  fullDescription: "Digamos que voce/agentes cheguem a uma melhoria ou novo arquivo os agentes entao podem salvar de forma autonoma no seu ambiente de desenvolvimento"
  UseCases: ""
 