version: "0.1"

tool_compose:
  id: "autochangesrequestedinpullrequest"
  type_plan: premium
  icon: "fas fa-pen-fancy text-xl"
  shortDescription: "Atualize um pull request com melhorias"
  fullDescription: "Digamos que voce abra um pull request com uma nova feature escrita rapidamente por meio dessa ferramenta o agente de code review pode revisar seu pr e atualiza-lo para as conformidades"
  UseCases: ""
 