version: "0.1"

tool_compose:
  id: "fetch_agent_metadata"
  type_plan: premium
  icon: "fas fa-database text-xl"
  shortDescription: "Busca metadados de múltiplos agentes no Firebase"
  fullDescription: >
    Esta ferramenta conecta-se ao Firebase Realtime Database usando credenciais
    fornecidas e recupera o bloco `metadata` de cada agente especificado. Útil para
    agentes de valuation ou orquestração que precisam consolidar informações de
    descrição, casos de uso e instruções de outros agentes.
  UseCases: >
    • Agentes de pricing/valuation que agregam dados de múltiplos agentes.
    • Ferramentas de auditoria para verificar consistência de metadados.
    • Dashboards que exibem resumo de todos os agentes registrados.
